import Footer from "@/Components/Footer";
import Header from "@/Components/Header";

import Menu from "@/Components/Menu";
export const metadata = {
  title: "Dashbored-AdminPanel",
  description: "Generated by create next app",
}

export default function DashboredLayout({ children }) {
  return (
    <main className="w-full flex flex-wrap font-myfont mx-auto 2xl:container bg-cover bg-no-repeat bg-myback bg-[#02021a]">
      <Menu />
      <section className="lg:w-[82%] w-full ml-auto">
        <Header />
        <div className="w-full">
          {children}
        </div>
      </section>
      <Footer />
    </main>
  )
}
